services:

  wss_db:
    image: postgres:16.3
    container_name: wss_db
    environment:
      POSTGRES_DB: wss_dev
      POSTGRES_USER: wss
      POSTGRES_PASSWORD: WSS
    ports:
      - "5432:5432"
    volumes:
      - wss_db_data:/var/lib/postgresql/data
  
  wss_db_admin:
    image: dpage/pgadmin4:latest
    container_name: wss_db_admin
    environment:
      PGADMIN_DEFAULT_EMAIL: wss@wss.com
      PGADMIN_DEFAULT_PASSWORD: 'WSS'
    ports:
      - "8080:80"
    volumes:
      - wss_db_admin_data:/var/lib/pgadmin

volumes:
  wss_db_data:
  wss_db_admin_data: